# Generated by Django 4.1.4 on 2023-05-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
